### ISSUE TITLE
localhost:8090 not working

### ISSUE THREAD

**Issue by fmello-cit** [ieiayaobb/dynamoc#1]
I followed instructions, all I see is a blank screen at localhost:8090.

**Comment by serendipity30** [comment]
yup..same issue here.

**Comment by ieiayaobb** [comment]
This project runs based on the electron, if you want to view in browser, please check this repository:
https://github.com/ieiayaobb/dynamoc_web

**Comment by fmello-cit** [comment]
Not sure if it was my misunderstanding, or documentation is not clear.
Anyway, thanks for the feedback.
